#include "PCH.h"

#include "Hook.h"
#include "LightOrderFix.h"
#include "LightPriorityFix.h"
#include "Settings.h"

namespace
{
	bool Load(const F4SE::LoadInterface* a_f4se)
	{
		// No trampoline: safetyhook manages its own.
		F4SE::Init(a_f4se, { .log = true });

		auto& settings = Settings::Get();
		settings.Load();

		// Hook::GetRuntime() answers VR itself; REX::FModule would terminate on
		// 1.2.72, so nothing here asks it directly.
		//
		// 1.10.980/984 shares the 1.11.x id space so every id resolves, but no such
		// binary was available to check the prologues against.  A mismatch refuses
		// to patch and logs, hence a warning rather than a refusal to load.
		const auto runtime = Hook::GetRuntime();
		if (runtime == Hook::Runtime::kNG) {
			REX::WARN("1.10.980/984 is untested; a bad address refuses to patch");
		}

		if (settings.lightOrderFix && !LightOrderFix::Install()) {
			REX::ERROR("light order fix could not be installed");
		}
		if (settings.lightPriorityFix && !LightPriorityFix::Install()) {
			REX::ERROR("light priority fix could not be installed");
		}

		REX::INFO("{} v{} loaded on {}{} (order fix {}, priority fix {})",
			F4SE::GetPluginName(), F4SE::GetPluginVersion(),
			REX::FModule::GetExecutingModule().GetFileVersion(),
			runtime == Hook::Runtime::kVR ? " (VR)" : "",
			settings.lightOrderFix ? "on" : "off",
			settings.lightPriorityFix ? "on" : "off");
		return true;
	}
}

// F4SE 0.7.x reads F4SEPlugin_Version, generated by the commonlibf4.plugin xmake
// rule: address-library and struct-layout dependent, no CompatibleVersions, so
// F4SE accepts it on any runtime it supports.  F4SE 0.6.23, which 1.10.163 needs,
// and F4SEVR 0.6.20, which is 0.6.x as well, predate that struct and ask for
// Query + Load instead, so both ABIs are exported and both reach Load above.
F4SE_PLUGIN_QUERY(const F4SE::QueryInterface* a_f4se, F4SE::PluginInfo* a_info)
{
	a_info->infoVersion = F4SE::PluginInfo::kVersion;
	a_info->name = "LightingFixes";
	a_info->version = 1;
	return !a_f4se->IsEditor();
}

F4SE_PLUGIN_LOAD(const F4SE::LoadInterface* a_f4se)
{
	return Load(a_f4se);
}
